# Pydantic schemas
from app.schemas.common import (
    MetaInfo,
    ErrorDetail,
    SuccessResponse,
    ErrorResponse,
    PaginationInfo,
    PaginatedResponse,
    ResourceIdResponse,
    MessageResponse,
    HealthResponse,
    StatsBase,
    PositionSchema,
    ItemQuantity,
    RewardSchema,
    ResourceAmount
)
from app.schemas.auth import (
    RegisterRequest,
    LoginRequest,
    RefreshTokenRequest,
    TokenResponse,
    ChangePasswordRequest,
    ResetPasswordRequest,
    ConfirmResetPasswordRequest
)
from app.schemas.player import (
    PlayerBase,
    PlayerCreate,
    PlayerUpdate,
    PlayerResponse,
    PlayerBriefResponse,
    PlayerStatsResponse,
    PlayerResourcesResponse,
    UpdateResourcesRequest,
    PlayerInventoryResponse
)
from app.schemas.hero import (
    HeroStatsResponse,
    HeroSkillResponse,
    HeroEquipmentSlots,
    HeroBase,
    HeroResponse,
    HeroBriefResponse,
    HeroListResponse,
    LevelUpRequest,
    LevelUpResponse,
    AscendRequest,
    AscendResponse,
    AwakenRequest,
    AwakenResponse,
    EquipRequest,
    EquipResponse,
    UnequipResponse,
    SkillUpgradeRequest,
    SkillUpgradeResponse,
    HeroFilterParams
)
from app.schemas.equipment import (
    EquipmentStatsResponse,
    SubstatSchema,
    EquipmentBase,
    EquipmentResponse,
    EquipmentBriefResponse,
    EquipmentListResponse,
    EnhanceRequest,
    EnhanceResponse,
    FuseRequest,
    FuseResponse,
    EquipmentFilterParams,
    EquipmentSetResponse
)
from app.schemas.battle import (
    CharacterStateResponse,
    StartBattleRequest,
    BattleStateResponse,
    ActionRequest,
    DamageDealtInfo,
    HealAmountInfo,
    EffectAppliedInfo,
    ActionResultResponse,
    BattleDropInfo,
    BattleResultResponse,
    BattleHistoryEntry,
    BattleHistoryResponse,
    AIActionResponse,
    BattleLogEntry,
    FullBattleLogResponse
)
